//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class NGODBEntities : DbContext
    {
        public NGODBEntities()
            : base("name=NGODBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbl_Cast> tbl_Cast { get; set; }
        public DbSet<tbl_District> tbl_District { get; set; }
        public DbSet<tbl_Gender> tbl_Gender { get; set; }
        public DbSet<tbl_Mandal> tbl_Mandal { get; set; }
        public DbSet<tbl_Notifications> tbl_Notifications { get; set; }
        public DbSet<tbl_Religion> tbl_Religion { get; set; }
        public DbSet<tbl_Roles> tbl_Roles { get; set; }
        public DbSet<tbl_Student_details> tbl_Student_details { get; set; }
        public DbSet<tbl_teacher_details> tbl_teacher_details { get; set; }
        public DbSet<tbl_Users> tbl_Users { get; set; }
        public DbSet<tbl_Village> tbl_Village { get; set; }
        public DbSet<tbl_Zone> tbl_Zone { get; set; }
        public DbSet<tbl_Address> tbl_Address { get; set; }
        public DbSet<tbl_schoolDetails> tbl_schoolDetails { get; set; }
    
        public virtual ObjectResult<proc_Notifications_Result> proc_Notifications(string xml, Nullable<int> type)
        {
            var xmlParameter = xml != null ?
                new ObjectParameter("xml", xml) :
                new ObjectParameter("xml", typeof(string));
    
            var typeParameter = type.HasValue ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_Notifications_Result>("proc_Notifications", xmlParameter, typeParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> proc_TeacherReg(string p_firstName, string p_middleName, string p_lastName, string p_email, string p_selectedGenderId, string p_contactno, string p_schoolName, string p_schoolAdd, string p_schoolDistrictId, string p_ScholZoneId, string p_schoolMandalid, string p_schoolVillage)
        {
            var p_firstNameParameter = p_firstName != null ?
                new ObjectParameter("p_firstName", p_firstName) :
                new ObjectParameter("p_firstName", typeof(string));
    
            var p_middleNameParameter = p_middleName != null ?
                new ObjectParameter("p_middleName", p_middleName) :
                new ObjectParameter("p_middleName", typeof(string));
    
            var p_lastNameParameter = p_lastName != null ?
                new ObjectParameter("p_lastName", p_lastName) :
                new ObjectParameter("p_lastName", typeof(string));
    
            var p_emailParameter = p_email != null ?
                new ObjectParameter("p_email", p_email) :
                new ObjectParameter("p_email", typeof(string));
    
            var p_selectedGenderIdParameter = p_selectedGenderId != null ?
                new ObjectParameter("p_selectedGenderId", p_selectedGenderId) :
                new ObjectParameter("p_selectedGenderId", typeof(string));
    
            var p_contactnoParameter = p_contactno != null ?
                new ObjectParameter("p_contactno", p_contactno) :
                new ObjectParameter("p_contactno", typeof(string));
    
            var p_schoolNameParameter = p_schoolName != null ?
                new ObjectParameter("p_schoolName", p_schoolName) :
                new ObjectParameter("p_schoolName", typeof(string));
    
            var p_schoolAddParameter = p_schoolAdd != null ?
                new ObjectParameter("p_schoolAdd", p_schoolAdd) :
                new ObjectParameter("p_schoolAdd", typeof(string));
    
            var p_schoolDistrictIdParameter = p_schoolDistrictId != null ?
                new ObjectParameter("p_schoolDistrictId", p_schoolDistrictId) :
                new ObjectParameter("p_schoolDistrictId", typeof(string));
    
            var p_ScholZoneIdParameter = p_ScholZoneId != null ?
                new ObjectParameter("p_ScholZoneId", p_ScholZoneId) :
                new ObjectParameter("p_ScholZoneId", typeof(string));
    
            var p_schoolMandalidParameter = p_schoolMandalid != null ?
                new ObjectParameter("p_schoolMandalid", p_schoolMandalid) :
                new ObjectParameter("p_schoolMandalid", typeof(string));
    
            var p_schoolVillageParameter = p_schoolVillage != null ?
                new ObjectParameter("p_schoolVillage", p_schoolVillage) :
                new ObjectParameter("p_schoolVillage", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("proc_TeacherReg", p_firstNameParameter, p_middleNameParameter, p_lastNameParameter, p_emailParameter, p_selectedGenderIdParameter, p_contactnoParameter, p_schoolNameParameter, p_schoolAddParameter, p_schoolDistrictIdParameter, p_ScholZoneIdParameter, p_schoolMandalidParameter, p_schoolVillageParameter);
        }
    }
}
