//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Gender
    {
        public tbl_Gender()
        {
            this.tbl_Student_details = new HashSet<tbl_Student_details>();
            this.tbl_teacher_details = new HashSet<tbl_teacher_details>();
        }
    
        public int GenderId { get; set; }
        public string GenderName { get; set; }
    
        public virtual ICollection<tbl_Student_details> tbl_Student_details { get; set; }
        public virtual ICollection<tbl_teacher_details> tbl_teacher_details { get; set; }
    }
}
